name: Action Test

on: [push]

jobs:
  action_test:
    
    runs-on: ubuntu-latest

    steps:
    - name: Set start timer
      run: |
        echo ::set-env name=START_TIME::$(date)
        echo ::set-env name=START_SECONDS::$(date +%s)

    - name: Self checkout 
      uses: actions/checkout@v2

    - name: Use the action in root
      uses: ./
      id: test
      with:
        message: 'Welcome Message'

    - name: Set output 
      run: echo "The time was ${{ steps.test.outputs.time }}"

    - name: Timings
      run: |
        echo "Start time:    $START_TIME"
        echo "End time:      $(date)"
        echo "Start seconds: $START_SECONDS"
        echo "End seconds:   $(date +%s)"       