name: Action Test

on: [push]

jobs:
  action_test:
    
    runs-on: ubuntu-18.04

    steps:

    - name: Self checkout
      uses: actions/checkout@v2

    - name: Use the action in root
      uses: ./
      id: test
      with:
        token: ${{ secrets.GITHUB_TOKEN }}